#include <sgx_urts.h>
#include "Enclave_u.h" // Untrusted header generated by the EDL

int main() {
    sgx_enclave_id_t enclave_id;
    sgx_status_t status;
    uint8_t data[] = { /* Your ZKP data */ };

    // Initialize the SGX enclave
    status = sgx_create_enclave("enclave.signed.so", SGX_DEBUG_FLAG, nullptr, nullptr, &enclave_id, nullptr);
    if (status != SGX_SUCCESS) {
        printf("Failed to create enclave.\n");
        return -1;
    }

    // Call the trusted function
    verify_zkp(enclave_id, data, sizeof(data));

    // Destroy the enclave
    sgx_destroy_enclave(enclave_id);
    return 0;
}
